#!/bin/sh

mkdir -p ~/.icu_1.0/ML/faces/
mkdir ~/.icu_1.0/ML/images/
mkdir -p ~/.icu_1.0/server/client_list/
touch ~/.icu_1.0/server/client_list/list.json
mkdir ~/.icu_1.0/server/message/

chown -R $(users):$(users) ~/.icu_1.0/
